=== folio-org/mod-linked-data/src/main/resources/swagger.api/folio-modules/inventory/inventoryInstanceEvent.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Inventory instance event data model",
  "javaType": "org.folio.rest.jaxrs.model.InventoryInstanceEvent",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "Id of the event",
      "$ref": "../common/uuid.json"
    },
    "new": {
      "description": "New state of the instance",
      "type": "object",
      "$ref": "inventoryInstance.json"
    },
    "old": {
      "description": "Old state of the instance",
      "type": "object",
      "$ref": "inventoryInstance.json"
    },
    "type": {
      "description": "Event type",
      "$ref": "../search/resourceIndexEventType.json"
    },
    "tenant": {
      "description": "Tenant id",
      "type": "string"
    },
    "ts": {
      "description": "Timestamp",
      "type": "string"
    }
  },
  "required": [
    "id"
  ],
  "excludedFromEqualsAndHashCode": [
    "tenant",
    "ts"
  ],
  "x-implements": "org.folio.spring.tools.kafka.BaseKafkaMessage"
}

=== folio-org/mod-linked-data/src/test/resources/samples/inventoryInstanceEvent.json
{
  "old":{
     "id":"302e2de6-3a13-4d87-a294-8fc01ec4bddf",
     "_version":4,
     "hrid":"in10391142",
     "source":"MARC",
     "title":"The \"\"Yoga Sutra of Patanjali\"\"A Biography.",
     "discoverySuppress":false
  },
  "new":{
     "id":"302e2de6-3a13-4d87-a294-8fc01ec4bddf",
     "_version":5,
     "hrid":"in10391142",
     "source":"MARC",
     "title":"The \"\"Yoga Sutra of Patanjali\"\"A Biography.",
     "staffSuppress":true,
     "discoverySuppress":true
  },
  "id" : "302e2de6-3a13-4d87-a294-8fc01ec4bddd",
  "type":"UPDATE",
  "tenant":"fs09000000"
}
